# Generated by Django 4.2.7 on 2026-02-03 08:00

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservations', '0003_alter_reservation_status'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='montant')),
                ('currency', models.CharField(default='XOF', max_length=3, verbose_name='devise')),
                ('status', models.CharField(choices=[('submitted', 'Soumis'), ('under_review', 'En cours de validation'), ('validated', 'Validé'), ('rejected', 'Rejeté')], default='submitted', max_length=20, verbose_name='statut')),
                ('payment_method_type', models.CharField(choices=[('card', 'Carte bancaire'), ('mobile_money', 'Mobile Money'), ('cash', 'Espèces'), ('bank_transfer', 'Virement bancaire'), ('wallet', 'Portefeuille')], max_length=20, verbose_name='type de paiement')),
                ('payment_details', models.JSONField(blank=True, default=dict, help_text='Informations de paiement cryptées', verbose_name='détails du paiement')),
                ('card_last_four', models.CharField(blank=True, help_text='4 derniers chiffres de la carte', max_length=4, verbose_name='4 derniers chiffres')),
                ('card_holder_name', models.CharField(blank=True, max_length=100, verbose_name='nom du porteur')),
                ('mobile_number', models.CharField(blank=True, max_length=20, verbose_name='numéro mobile')),
                ('mobile_provider', models.CharField(blank=True, help_text='Orange, MTN, Moov, etc.', max_length=50, verbose_name='opérateur mobile')),
                ('submission_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de soumission')),
                ('user_agent', models.TextField(blank=True, verbose_name='user agent')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='raison du rejet')),
                ('validated_at', models.DateTimeField(blank=True, null=True, verbose_name='date de validation')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date de mise à jour')),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_submission', to='reservations.reservation', verbose_name='réservation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_submissions', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_payment_submissions', to=settings.AUTH_USER_MODEL, verbose_name='validé par')),
            ],
            options={
                'verbose_name': 'soumission de paiement',
                'verbose_name_plural': 'soumissions de paiement',
                'ordering': ['-created_at'],
            },
        ),
    ]
