# Generated by Django 4.2.7 on 2026-02-20 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_invoice'),
        ('payments', '0002_paymentsubmission'),
    ]

    operations = [
    ]
