# Generated by Django 4.2.7 on 2026-02-05 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('fr', 'Français'), ('en', 'English'), ('es', 'Español'), ('ar', 'العربية')], default='fr', max_length=10, verbose_name='Langue')),
                ('theme', models.CharField(choices=[('light', 'Clair'), ('dark', 'Sombre'), ('auto', 'Automatique')], default='light', max_length=10, verbose_name='Thème')),
                ('timezone', models.CharField(default='Africa/Ndjamena', max_length=50, verbose_name='Fuseau horaire')),
                ('currency', models.CharField(choices=[('XAF', 'FCFA'), ('EUR', 'Euro'), ('USD', 'Dollar')], default='XAF', max_length=3, verbose_name='Devise')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='Notifications par email')),
                ('sms_notifications', models.BooleanField(default=False, verbose_name='Notifications par SMS')),
                ('push_notifications', models.BooleanField(default=True, verbose_name='Notifications push')),
                ('public_profile', models.BooleanField(default=True, verbose_name='Profil public')),
                ('show_email', models.BooleanField(default=True, verbose_name='Afficher email dans profil')),
                ('show_phone', models.BooleanField(default=False, verbose_name='Afficher téléphone dans profil')),
                ('allow_friend_requests', models.BooleanField(default=True, verbose_name="Autoriser demandes d'amis")),
                ('data_analytics', models.BooleanField(default=False, verbose_name='Participer aux analytics')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Préférences utilisateur',
                'verbose_name_plural': 'Préférences utilisateurs',
            },
        ),
    ]
