# Generated by Django 4.2.7 on 2025-12-14 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('activity_type', models.CharField(choices=[('training', 'Entraînement'), ('match', 'Match'), ('tournament', 'Tournoi'), ('other', 'Autre')], max_length=20, verbose_name="type d'activité")),
                ('max_participants', models.PositiveIntegerField(verbose_name='nombre maximum de participants')),
                ('start_time', models.DateTimeField(verbose_name='date et heure de début')),
                ('end_time', models.DateTimeField(verbose_name='date et heure de fin')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmé'), ('cancelled', 'Annulé'), ('completed', 'Terminé')], default='pending', max_length=20, verbose_name='statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date de mise à jour')),
            ],
            options={
                'verbose_name': 'activité',
                'verbose_name_plural': 'activités',
                'ordering': ['-start_time'],
            },
        ),
    ]
