# Generated by Django 4.2.7 on 2025-12-14 02:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
        ('terrains', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_activities', to=settings.AUTH_USER_MODEL, verbose_name='entraîneur'),
        ),
        migrations.AddField(
            model_name='activity',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participating_activities', to=settings.AUTH_USER_MODEL, verbose_name='participants'),
        ),
        migrations.AddField(
            model_name='activity',
            name='terrain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='terrains.terrain', verbose_name='terrain'),
        ),
    ]
