# Generated by Django 4.2.7 on 2026-02-07 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terrains', '0004_terrain_latitude_terrain_longitude'),
        ('activities', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='terrain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_events', to='terrains.terrain', verbose_name='terrain'),
        ),
    ]
