# Generated by Django 4.2.7 on 2026-01-28 08:17

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('terrains', '0003_add_image_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservations', '0003_alter_reservation_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitingList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='date souhaitée')),
                ('start_time', models.TimeField(verbose_name='heure de début souhaitée')),
                ('end_time', models.TimeField(verbose_name='heure de fin souhaitée')),
                ('duration_minutes', models.PositiveIntegerField(verbose_name='durée en minutes')),
                ('priority', models.CharField(choices=[('low', 'Faible'), ('normal', 'Normal'), ('high', 'Élevé'), ('urgent', 'Urgent')], default='normal', max_length=20, verbose_name='priorité')),
                ('status', models.CharField(choices=[('waiting', 'En attente'), ('notified', 'Notifié'), ('accepted', 'Accepté'), ('declined', 'Décliné'), ('expired', 'Expiré'), ('cancelled', 'Annulé')], default='waiting', max_length=20, verbose_name='statut')),
                ('flexible_times', models.BooleanField(default=True, help_text="Accepte des créneaux proches de l'heure souhaitée", verbose_name='horaires flexibles')),
                ('max_time_difference', models.PositiveIntegerField(default=60, help_text="Différence maximale acceptée par rapport à l'heure souhaitée", verbose_name="différence max d'heure (minutes)")),
                ('flexible_date', models.BooleanField(default=False, help_text='Accepte des dates proches de la date souhaitée', verbose_name='date flexible')),
                ('max_date_difference', models.PositiveIntegerField(default=0, help_text='Différence maximale acceptée par rapport à la date souhaitée', verbose_name='différence max de date (jours)')),
                ('notification_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='date de notification')),
                ('notification_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='expiration notification')),
                ('notification_count', models.PositiveIntegerField(default=0, verbose_name='nombre de notifications')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('admin_notes', models.TextField(blank=True, verbose_name='notes admin')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date de mise à jour')),
                ('reservation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waiting_list_entry', to='reservations.reservation', verbose_name='réservation associée')),
                ('terrain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiting_list_entries', to='terrains.terrain', verbose_name='terrain')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiting_list_entries', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': "liste d'attente",
                'verbose_name_plural': "listes d'attente",
                'ordering': ['terrain', 'date', 'priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='WaitingListNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('timeslot_available', 'Créneau disponible'), ('reminder', 'Rappel'), ('expiry_warning', 'Avertissement expiration')], max_length=50, verbose_name='type de notification')),
                ('proposed_timeslot_id', models.UUIDField(blank=True, null=True, verbose_name='ID créneau proposé')),
                ('proposed_date', models.DateField(blank=True, null=True, verbose_name='date proposée')),
                ('proposed_start_time', models.TimeField(blank=True, null=True, verbose_name='heure début proposée')),
                ('proposed_end_time', models.TimeField(blank=True, null=True, verbose_name='heure fin proposée')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name="date d'envoi")),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='date de lecture')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='date de réponse')),
                ('response', models.CharField(blank=True, choices=[('accepted', 'Accepté'), ('declined', 'Décliné'), ('expired', 'Expiré')], max_length=20, null=True, verbose_name='réponse')),
                ('message', models.TextField(verbose_name='message')),
                ('response_message', models.TextField(blank=True, verbose_name='message réponse')),
                ('waiting_list_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='waitinglist.waitinglist', verbose_name="entrée liste d'attente")),
            ],
            options={
                'verbose_name': "notification liste d'attente",
                'verbose_name_plural': "notifications liste d'attente",
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='WaitingListConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='activée')),
                ('max_entries_per_day', models.PositiveIntegerField(default=50, help_text="Nombre maximum d'entrées dans la liste d'attente par jour", verbose_name='max entrées par jour')),
                ('notification_hours_before', models.PositiveIntegerField(default=24, help_text="Nombre d'heures avant le créneau pour notifier", verbose_name='heures avant notification')),
                ('notification_expiry_hours', models.PositiveIntegerField(default=24, help_text='Durée de validité de la notification', verbose_name='heures expiration notification')),
                ('max_notifications_per_user', models.PositiveIntegerField(default=3, help_text='Nombre maximum de notifications par utilisateur', verbose_name='max notifications par utilisateur')),
                ('enable_priority_scoring', models.BooleanField(default=True, verbose_name='scoring priorité automatique')),
                ('vip_score_bonus', models.PositiveIntegerField(default=100, verbose_name='bonus score VIP')),
                ('frequent_user_score_bonus', models.PositiveIntegerField(default=50, verbose_name='bonus score utilisateur fréquent')),
                ('long_waiting_score_bonus', models.PositiveIntegerField(default=10, verbose_name='bonus score longue attente')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date de mise à jour')),
                ('terrain', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='waiting_list_config', to='terrains.terrain', verbose_name='terrain')),
            ],
            options={
                'verbose_name': "configuration liste d'attente",
                'verbose_name_plural': "configurations liste d'attente",
            },
        ),
        migrations.CreateModel(
            name='WaitingListStatistics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='date')),
                ('total_entries', models.PositiveIntegerField(default=0, verbose_name='total entrées')),
                ('new_entries', models.PositiveIntegerField(default=0, verbose_name='nouvelles entrées')),
                ('resolved_entries', models.PositiveIntegerField(default=0, verbose_name='entrées résolues')),
                ('entries_by_priority', models.JSONField(blank=True, default=dict, verbose_name='entrées par priorité')),
                ('entries_by_status', models.JSONField(blank=True, default=dict, verbose_name='entrées par statut')),
                ('notifications_sent', models.PositiveIntegerField(default=0, verbose_name='notifications envoyées')),
                ('notifications_accepted', models.PositiveIntegerField(default=0, verbose_name='notifications acceptées')),
                ('notifications_declined', models.PositiveIntegerField(default=0, verbose_name='notifications déclinées')),
                ('avg_waiting_time_hours', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, verbose_name="temps d'attente moyen (heures)")),
                ('conversion_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text="Pourcentage d'entrées converties en réservations", max_digits=5, verbose_name='taux de conversion')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date de mise à jour')),
                ('terrain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiting_list_statistics', to='terrains.terrain', verbose_name='terrain')),
            ],
            options={
                'verbose_name': "statistiques liste d'attente",
                'verbose_name_plural': "statistiques liste d'attente",
                'ordering': ['-date'],
                'unique_together': {('terrain', 'date')},
            },
        ),
        migrations.AddIndex(
            model_name='waitinglist',
            index=models.Index(fields=['terrain', 'date', 'status'], name='waitinglist_terrain_7cd75e_idx'),
        ),
        migrations.AddIndex(
            model_name='waitinglist',
            index=models.Index(fields=['user', 'status'], name='waitinglist_user_id_9c43e5_idx'),
        ),
        migrations.AddIndex(
            model_name='waitinglist',
            index=models.Index(fields=['priority', 'created_at'], name='waitinglist_priorit_d2cacb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='waitinglist',
            unique_together={('user', 'terrain', 'date', 'start_time', 'end_time')},
        ),
    ]
