# Generated by Django 4.2.7 on 2026-01-28 08:17

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('terrains', '0003_add_image_field'),
        ('reservations', '0003_alter_reservation_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='nom')),
                ('date', models.DateField(verbose_name='date')),
                ('day_type', models.CharField(choices=[('weekday', 'Jour de semaine'), ('weekend', 'Week-end'), ('holiday', 'Jour férié'), ('special', 'Jour spécial')], default='holiday', max_length=20, verbose_name='type de jour')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='récurrent')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
            ],
            options={
                'verbose_name': 'jour férié',
                'verbose_name_plural': 'jours fériés',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='PricingAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='date')),
                ('avg_price_per_hour', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='prix moyen par heure')),
                ('min_price_per_hour', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='prix minimum par heure')),
                ('max_price_per_hour', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='prix maximum par heure')),
                ('total_reservations', models.PositiveIntegerField(default=0, verbose_name='total réservations')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='revenu total')),
                ('rules_applied_count', models.PositiveIntegerField(default=0, verbose_name='règles appliquées')),
                ('most_used_rule', models.CharField(blank=True, max_length=100, verbose_name='règle la plus utilisée')),
                ('occupancy_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name="taux d'occupation")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date de mise à jour')),
                ('terrain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_analytics', to='terrains.terrain', verbose_name='terrain')),
            ],
            options={
                'verbose_name': 'analytique de tarification',
                'verbose_name_plural': 'analytiques de tarification',
                'ordering': ['-date'],
                'unique_together': {('terrain', 'date')},
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='prix de base')),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='prix final')),
                ('applied_rules', models.JSONField(blank=True, default=list, verbose_name='règles appliquées')),
                ('price_adjustments', models.JSONField(blank=True, default=dict, verbose_name='ajustements de prix')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='reservations.reservation', verbose_name='réservation')),
                ('terrain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='terrains.terrain', verbose_name='terrain')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_history', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'historique de prix',
                'verbose_name_plural': 'historiques de prix',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['terrain', 'created_at'], name='pricing_pri_terrain_dbd46e_idx'), models.Index(fields=['reservation'], name='pricing_pri_reserva_c9d8fb_idx')],
            },
        ),
        migrations.CreateModel(
            name='DynamicPricingRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='nom')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('rule_type', models.CharField(choices=[('multiplier', 'Multiplicateur'), ('fixed_amount', 'Montant fixe'), ('percentage', 'Pourcentage'), ('tiered', 'Paliers')], max_length=20, verbose_name='type de règle')),
                ('priority', models.PositiveIntegerField(default=0, help_text='Plus la priorité est élevée, plus la règle est importante', verbose_name='priorité')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='date de début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='date de fin')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='heure de début')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='heure de fin')),
                ('day_types', models.JSONField(blank=True, default=list, help_text='Liste des types de jours concernés', verbose_name='types de jours')),
                ('min_duration_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='durée minimale (minutes)')),
                ('max_duration_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='durée maximale (minutes)')),
                ('min_advance_days', models.PositiveIntegerField(blank=True, null=True, verbose_name="jours minimum à l'avance")),
                ('max_advance_days', models.PositiveIntegerField(blank=True, null=True, verbose_name="jours maximum à l'avance")),
                ('multiplier_value', models.DecimalField(decimal_places=3, default=Decimal('1.000'), help_text='Multiplicateur appliqué au prix de base', max_digits=5, verbose_name='multiplicateur')),
                ('fixed_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Montant fixe à ajouter ou soustraire', max_digits=10, null=True, verbose_name='montant fixe')),
                ('percentage_value', models.DecimalField(blank=True, decimal_places=2, help_text="Pourcentage d'augmentation ou de réduction", max_digits=5, null=True, verbose_name='pourcentage')),
                ('tier_config', models.JSONField(blank=True, default=dict, help_text='Configuration pour les tarifs par paliers', verbose_name='configuration des paliers')),
                ('max_applications_per_day', models.PositiveIntegerField(blank=True, null=True, verbose_name='max applications par jour')),
                ('max_applications_per_user', models.PositiveIntegerField(blank=True, null=True, verbose_name='max applications par utilisateur')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date de mise à jour')),
                ('terrain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_pricing_rules', to='terrains.terrain', verbose_name='terrain')),
            ],
            options={
                'verbose_name': 'règle de tarification dynamique',
                'verbose_name_plural': 'règles de tarification dynamique',
                'ordering': ['-priority', 'created_at'],
                'indexes': [models.Index(fields=['terrain', 'is_active'], name='pricing_dyn_terrain_1fe384_idx'), models.Index(fields=['start_date', 'end_date'], name='pricing_dyn_start_d_8c6e78_idx'), models.Index(fields=['priority'], name='pricing_dyn_priorit_b23bae_idx')],
            },
        ),
    ]
