# Generated by Django 4.2.7 on 2025-12-14 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Terrain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nom')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('terrain_type', models.CharField(choices=[('football', 'Football'), ('tennis', 'Tennis'), ('basketball', 'Basketball'), ('volleyball', 'Volleyball'), ('handball', 'Handball')], max_length=20, verbose_name='type de terrain')),
                ('capacity', models.PositiveIntegerField(verbose_name='capacité')),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='prix par heure')),
                ('is_available', models.BooleanField(default=True, verbose_name='disponible')),
                ('image', models.ImageField(blank=True, null=True, upload_to='terrain_images/', verbose_name='image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date de mise à jour')),
            ],
            options={
                'verbose_name': 'terrain',
                'verbose_name_plural': 'terrains',
                'ordering': ['name'],
            },
        ),
    ]
