# Generated by Django 4.2.7 on 2025-12-22 02:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('terrains', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nom')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('icon', models.CharField(help_text='Classe Font Awesome', max_length=50, verbose_name='icône')),
            ],
            options={
                'verbose_name': 'équipement',
                'verbose_name_plural': 'équipements',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='terrain',
            name='image',
        ),
        migrations.RemoveField(
            model_name='terrain',
            name='is_available',
        ),
        migrations.AddField(
            model_name='terrain',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='note moyenne'),
        ),
        migrations.AddField(
            model_name='terrain',
            name='status',
            field=models.CharField(choices=[('available', 'Disponible'), ('maintenance', 'En maintenance'), ('closed', 'Fermé')], default='available', max_length=20, verbose_name='statut'),
        ),
        migrations.CreateModel(
            name='TerrainPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='terrain_photos/', verbose_name='image')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='légende')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ordre')),
                ('is_primary', models.BooleanField(default=False, verbose_name='photo principale')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="date d'ajout")),
                ('terrain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='terrains.terrain', verbose_name='terrain')),
            ],
            options={
                'verbose_name': 'photo de terrain',
                'verbose_name_plural': 'photos de terrain',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MaintenancePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='date de début')),
                ('end_date', models.DateTimeField(verbose_name='date de fin')),
                ('reason', models.TextField(blank=True, verbose_name='raison')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('terrain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_periods', to='terrains.terrain', verbose_name='terrain')),
            ],
            options={
                'verbose_name': 'période de maintenance',
                'verbose_name_plural': 'périodes de maintenance',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='TerrainEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='quantité')),
                ('condition', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Bon'), ('fair', 'Moyen'), ('poor', 'Mauvais')], default='good', max_length=20, verbose_name='état')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terrains.equipment', verbose_name='équipement')),
                ('terrain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terrain_equipments', to='terrains.terrain', verbose_name='terrain')),
            ],
            options={
                'verbose_name': 'équipement de terrain',
                'verbose_name_plural': 'équipements de terrain',
                'unique_together': {('terrain', 'equipment')},
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='note')),
                ('comment', models.TextField(blank=True, verbose_name='commentaire')),
                ('is_approved', models.BooleanField(default=True, verbose_name='approuvé')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date de mise à jour')),
                ('terrain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='terrains.terrain', verbose_name='terrain')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'avis',
                'verbose_name_plural': 'avis',
                'ordering': ['-created_at'],
                'unique_together': {('terrain', 'user')},
            },
        ),
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveIntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')], verbose_name='jour de la semaine')),
                ('opening_time', models.TimeField(verbose_name="heure d'ouverture")),
                ('closing_time', models.TimeField(verbose_name='heure de fermeture')),
                ('is_closed', models.BooleanField(default=False, verbose_name='fermé')),
                ('terrain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_hours', to='terrains.terrain', verbose_name='terrain')),
            ],
            options={
                'verbose_name': "horaire d'ouverture",
                'verbose_name_plural': "horaires d'ouverture",
                'ordering': ['day_of_week', 'opening_time'],
                'unique_together': {('terrain', 'day_of_week')},
            },
        ),
    ]
