# Generated by Django 4.2.7 on 2026-01-26 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terrains', '0002_equipment_remove_terrain_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='terrain',
            name='image',
            field=models.URLField(blank=True, help_text="URL de l'image principale du terrain", max_length=500, null=True, verbose_name='image principale'),
        ),
    ]
