# Generated by Django 4.2.7 on 2026-01-30 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terrains', '0003_add_image_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='terrain',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude du terrain (ex: 48.8566)', max_digits=9, null=True, verbose_name='latitude'),
        ),
        migrations.AddField(
            model_name='terrain',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude du terrain (ex: 2.3522)', max_digits=9, null=True, verbose_name='longitude'),
        ),
    ]
