# Generated by Django 4.2.7 on 2025-12-15 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmée'), ('rejected', 'Rejetée'), ('cancelled', 'Annulée'), ('completed', 'Terminée')], default='pending', max_length=20, verbose_name='statut'),
        ),
    ]
