# Generated by Django 4.2.7 on 2026-02-07 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_alter_activity_terrain'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservations', '0003_alter_reservation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='activities.activity', verbose_name='activité liée'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='confirmation_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date de confirmation'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_reservations', to=settings.AUTH_USER_MODEL, verbose_name='confirmé par'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date de paiement'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Espèces'), ('card', 'Carte bancaire'), ('mobile_money', 'Mobile Money'), ('transfer', 'Virement bancaire')], max_length=20, verbose_name='méthode de paiement'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='prix par heure'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='titre'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='identifiant de transaction'),
        ),
    ]
