# Generated by Django 4.2.7 on 2026-02-11 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_reservation_activity_reservation_confirmation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='montant total'),
        ),
    ]
