# Generated by Django 4.2.7 on 2026-01-28 08:17

import datetime
from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('terrains', '0003_add_image_field'),
        ('reservations', '0003_alter_reservation_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditPackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='nom')),
                ('description', models.TextField(verbose_name='description')),
                ('credit_amount', models.PositiveIntegerField(help_text='Nombre de crédits inclus dans le forfait', verbose_name='nombre de crédits')),
                ('credit_type', models.CharField(choices=[('hours', 'Heures'), ('reservations', 'Réservations'), ('minutes', 'Minutes')], default='hours', max_length=20, verbose_name='type de crédits')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='prix')),
                ('currency', models.CharField(default='XOF', max_length=3, verbose_name='devise')),
                ('bonus_credits', models.PositiveIntegerField(default=0, help_text='Crédits supplémentaires offerts', verbose_name='crédits bonus')),
                ('validity_days', models.PositiveIntegerField(blank=True, help_text='Nombre de jours avant expiration des crédits', null=True, verbose_name='validité en jours')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('is_popular', models.BooleanField(default=False, verbose_name='populaire')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date de mise à jour')),
            ],
            options={
                'verbose_name': 'forfait de crédits',
                'verbose_name_plural': 'forfaits de crédits',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='nom')),
                ('description', models.TextField(verbose_name='description')),
                ('membership_type', models.CharField(choices=[('individual', 'Individuel'), ('family', 'Familial'), ('corporate', 'Entreprise'), ('student', 'Étudiant'), ('senior', 'Senior')], max_length=20, verbose_name="type d'abonnement")),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='prix de base')),
                ('currency', models.CharField(default='XOF', max_length=3, verbose_name='devise')),
                ('duration_days', models.PositiveIntegerField(help_text="Durée de l'abonnement en jours", verbose_name='durée en jours')),
                ('recurrence_type', models.CharField(choices=[('daily', 'Quotidien'), ('weekly', 'Hebdomadaire'), ('monthly', 'Mensuel'), ('quarterly', 'Trimestriel'), ('yearly', 'Annuel')], help_text='Type de renouvellement automatique', max_length=20, verbose_name='type de récurrence')),
                ('max_reservations_per_month', models.PositiveIntegerField(blank=True, help_text='Nombre maximum de réservations incluses par mois', null=True, verbose_name='max réservations par mois')),
                ('max_reservations_per_week', models.PositiveIntegerField(blank=True, help_text='Nombre maximum de réservations incluses par semaine', null=True, verbose_name='max réservations par semaine')),
                ('included_hours_per_month', models.PositiveIntegerField(blank=True, help_text="Nombre d'heures incluses par mois", null=True, verbose_name='heures incluses par mois')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Réduction appliquée sur les réservations', max_digits=5, verbose_name='pourcentage de réduction')),
                ('free_cancellation_hours', models.PositiveIntegerField(default=24, help_text="Nombre d'heures avant la réservation pour annulation gratuite", verbose_name="heures d'annulation gratuite")),
                ('max_booking_days_in_advance', models.PositiveIntegerField(blank=True, null=True, verbose_name="jours max de réservation à l'avance")),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('is_public', models.BooleanField(default=True, verbose_name='public')),
                ('requires_approval', models.BooleanField(default=False, verbose_name='requiert validation')),
                ('max_subscribers', models.PositiveIntegerField(blank=True, help_text="Nombre maximum d'abonnés autorisés", null=True, verbose_name='max abonnés')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date de mise à jour')),
                ('allowed_terrains', models.ManyToManyField(blank=True, related_name='memberships', to='terrains.terrain', verbose_name='terrains autorisés')),
            ],
            options={
                'verbose_name': "type d'abonnement",
                'verbose_name_plural': "types d'abonnements",
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RecurringReservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recurrence_pattern', models.JSONField(help_text='Configuration de la récurrence (RRULE format)', verbose_name='pattern de récurrence')),
                ('start_time', models.TimeField(verbose_name='heure de début')),
                ('end_time', models.TimeField(verbose_name='heure de fin')),
                ('duration_minutes', models.PositiveIntegerField(verbose_name='durée en minutes')),
                ('start_date', models.DateField(verbose_name='date de début')),
                ('end_date', models.DateField(verbose_name='date de fin')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date de mise à jour')),
                ('generated_reservations', models.ManyToManyField(blank=True, related_name='recurring_pattern', to='reservations.reservation', verbose_name='réservations générées')),
                ('terrain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_reservations', to='terrains.terrain', verbose_name='terrain')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_reservations', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'réservation récurrente',
                'verbose_name_plural': 'réservations récurrentes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserCredit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='montant')),
                ('credit_type', models.CharField(choices=[('hours', 'Heures'), ('reservations', 'Réservations'), ('minutes', 'Minutes')], max_length=20, verbose_name='type de crédits')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name="date d'expiration")),
                ('transaction_id', models.CharField(blank=True, max_length=100, verbose_name='ID transaction')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date de mise à jour')),
                ('credit_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_credits', to='subscriptions.creditpackage', verbose_name="forfait d'origine")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'crédit utilisateur',
                'verbose_name_plural': 'crédits utilisateurs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'credit_type'], name='subscriptio_user_id_d38870_idx'), models.Index(fields=['expires_at'], name='subscriptio_expires_8415a9_idx')],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField(verbose_name='date de début')),
                ('end_date', models.DateTimeField(verbose_name='date de fin')),
                ('status', models.CharField(choices=[('active', 'Actif'), ('inactive', 'Inactif'), ('suspended', 'Suspendu'), ('cancelled', 'Annulé'), ('expired', 'Expiré')], default='active', max_length=20, verbose_name='statut')),
                ('price_paid', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='prix payé')),
                ('currency', models.CharField(default='XOF', max_length=3, verbose_name='devise')),
                ('reservations_used_this_month', models.PositiveIntegerField(default=0, verbose_name='réservations utilisées ce mois')),
                ('hours_used_this_month', models.PositiveIntegerField(default=0, verbose_name='heures utilisées ce mois')),
                ('last_usage_reset', models.DateField(default=datetime.date.today, verbose_name='dernière réinitialisation usage')),
                ('auto_renew', models.BooleanField(default=True, verbose_name='auto-renouvellement')),
                ('approval_notes', models.TextField(blank=True, verbose_name='notes de validation')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date de mise à jour')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='validé par')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='subscriptions.membership', verbose_name="type d'abonnement")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'abonnement',
                'verbose_name_plural': 'abonnements',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='subscriptio_user_id_2a19e8_idx'), models.Index(fields=['membership', 'status'], name='subscriptio_members_8497a6_idx'), models.Index(fields=['end_date'], name='subscriptio_end_dat_60694b_idx')],
            },
        ),
    ]
