# Generated by Django 4.2.7 on 2026-01-28 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0003_alter_reservation_status'),
        ('terrains', '0003_add_image_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlotGeneration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField(verbose_name='date de début')),
                ('end_date', models.DateField(verbose_name='date de fin')),
                ('slot_duration', models.PositiveIntegerField(help_text='Durée en minutes', verbose_name='durée des créneaux')),
                ('slots_generated', models.PositiveIntegerField(verbose_name='nombre de créneaux générés')),
                ('generation_method', models.CharField(choices=[('automatic', 'Automatique'), ('manual', 'Manuelle'), ('bulk', 'Massive')], max_length=50, verbose_name='méthode de génération')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slot_generations', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('terrain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_generations', to='terrains.terrain', verbose_name='terrain')),
            ],
            options={
                'verbose_name': 'génération de créneaux',
                'verbose_name_plural': 'générations de créneaux',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimeSlotBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_datetime', models.DateTimeField(verbose_name='date et heure de début')),
                ('end_datetime', models.DateTimeField(verbose_name='date et heure de fin')),
                ('reason', models.TextField(verbose_name='raison du blocage')),
                ('is_maintenance', models.BooleanField(default=False, verbose_name='maintenance')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slot_blocks', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('terrain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_blocks', to='terrains.terrain', verbose_name='terrain')),
            ],
            options={
                'verbose_name': 'blocage de créneau',
                'verbose_name_plural': 'blocages de créneaux',
                'ordering': ['terrain', 'start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='AvailabilityRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_type', models.CharField(choices=[('block', 'Bloquer'), ('available', 'Rendre disponible'), ('price_override', 'Modifier le prix')], max_length=20, verbose_name='type de règle')),
                ('name', models.CharField(max_length=100, verbose_name='nom')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('priority', models.PositiveIntegerField(default=0, help_text='Plus la priorité est élevée, plus la règle est importante', verbose_name='priorité')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='date de début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='date de fin')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='heure de début')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='heure de fin')),
                ('monday', models.BooleanField(default=False, verbose_name='lundi')),
                ('tuesday', models.BooleanField(default=False, verbose_name='mardi')),
                ('wednesday', models.BooleanField(default=False, verbose_name='mercredi')),
                ('thursday', models.BooleanField(default=False, verbose_name='jeudi')),
                ('friday', models.BooleanField(default=False, verbose_name='vendredi')),
                ('saturday', models.BooleanField(default=False, verbose_name='samedi')),
                ('sunday', models.BooleanField(default=False, verbose_name='dimanche')),
                ('price_multiplier', models.DecimalField(decimal_places=2, default=1.0, help_text='Multiplie le prix par défaut (ex: 1.5 pour +50%)', max_digits=5, verbose_name='multiplicateur de prix')),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, help_text='Prix fixe qui remplace le prix par défaut', max_digits=10, null=True, verbose_name='prix fixe')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date de mise à jour')),
                ('terrain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_rules', to='terrains.terrain', verbose_name='terrain')),
            ],
            options={
                'verbose_name': 'règle de disponibilité',
                'verbose_name_plural': 'règles de disponibilité',
                'ordering': ['terrain', 'priority'],
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='date')),
                ('start_time', models.TimeField(verbose_name='heure de début')),
                ('end_time', models.TimeField(verbose_name='heure de fin')),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('booked', 'Réservé'), ('blocked', 'Bloqué'), ('maintenance', 'Maintenance'), ('unavailable', 'Indisponible')], default='available', max_length=20, verbose_name='statut')),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, help_text='Prix spécifique pour ce créneau (remplace le prix par défaut)', max_digits=10, null=True, verbose_name='prix personnalisé')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='récurrent')),
                ('recurring_pattern', models.JSONField(blank=True, default=dict, help_text='Configuration de la récurrence', verbose_name='pattern de récurrence')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date de mise à jour')),
                ('reservation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeslot', to='reservations.reservation', verbose_name='réservation')),
                ('terrain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeslots', to='terrains.terrain', verbose_name='terrain')),
            ],
            options={
                'verbose_name': 'créneau horaire',
                'verbose_name_plural': 'créneaux horaires',
                'ordering': ['terrain', 'date', 'start_time'],
                'indexes': [models.Index(fields=['terrain', 'date', 'status'], name='timeslots_t_terrain_e270b6_idx'), models.Index(fields=['date', 'start_time'], name='timeslots_t_date_bd5427_idx'), models.Index(fields=['status'], name='timeslots_t_status_15d48e_idx')],
                'unique_together': {('terrain', 'date', 'start_time', 'end_time')},
            },
        ),
    ]
