# Generated by Django 4.2.7 on 2026-02-10 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservations', '0004_reservation_activity_reservation_confirmation_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(max_length=20, unique=True, verbose_name='numéro de ticket')),
                ('qr_code', models.ImageField(upload_to='tickets/qr_codes/', verbose_name='code QR')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='date de génération')),
                ('is_used', models.BooleanField(default=False, verbose_name='utilisé')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name="date d'utilisation")),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='reservations.reservation', verbose_name='réservation')),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='utilisé par')),
            ],
            options={
                'verbose_name': 'ticket',
                'verbose_name_plural': 'tickets',
                'ordering': ['-generated_at'],
            },
        ),
    ]
