# Generated by Django 4.2.7 on 2026-02-16 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_ticket_id'),
    ]

    operations = [
    ]
