# Generated by Django 4.2.7 on 2025-12-15 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('message', models.TextField(verbose_name='message')),
                ('notification_type', models.CharField(choices=[('reservation_pending', 'Nouvelle réservation en attente'), ('reservation_confirmed', 'Réservation confirmée'), ('reservation_rejected', 'Réservation rejetée'), ('reservation_cancelled', 'Réservation annulée'), ('activity_reminder', "Rappel d'activité"), ('activity_cancelled', 'Activité annulée'), ('activity_modified', 'Activité modifiée'), ('system_message', 'Message système')], max_length=30, verbose_name='type de notification')),
                ('priority', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyenne'), ('high', 'Haute'), ('urgent', 'Urgente')], default='medium', max_length=10, verbose_name='priorité')),
                ('is_read', models.BooleanField(default=False, verbose_name='lue')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='date de lecture')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='destinataire')),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('reservation_pending', 'Nouvelle réservation en attente'), ('reservation_confirmed', 'Réservation confirmée'), ('reservation_rejected', 'Réservation rejetée'), ('reservation_cancelled', 'Réservation annulée'), ('activity_reminder', "Rappel d'activité"), ('activity_cancelled', 'Activité annulée'), ('activity_modified', 'Activité modifiée'), ('system_message', 'Message système')], max_length=30, verbose_name='type de notification')),
                ('email_enabled', models.BooleanField(default=True, verbose_name='notification par email')),
                ('push_enabled', models.BooleanField(default=True, verbose_name='notification push')),
                ('in_app_enabled', models.BooleanField(default=True, verbose_name='notification in-app')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'préférence de notification',
                'verbose_name_plural': 'préférences de notification',
                'unique_together': {('user', 'notification_type')},
            },
        ),
    ]
